### ISSUE TITLE
UI/UX issue:   Departure Time input prompt needs rework.

### ISSUE THREAD

**Issue by tkim013** [LightingWolf/Boarding-Pass-Project#26]
> Enter your Departure Time: 
> HH:mm AM/PM
> Please enter a time with the expected format: 
> Example: HH:MM AM/PM ->  02:34 PM
> Please enter a time with the expected format: 
> Example: HH:MM AM/PM ->  02:34 PM

Please enter a time with the expected format: 
Example: HH:MM AM/PM ->  02:34 PM
Initial input prompt repeats itself.

> HH:mm AM/PM

is unnecessary when:

> Please enter a time with the expected format: 
> Example: HH:MM AM/PM ->  02:34 PM

already exists.

someone other than Robert or Alex handle this for practice

Right side of this screen under Assignees, assign yourself to this issue. Leave a comment like "I'll handle this."
Right side of this screen under Development, create a branch. Resolve issue and create pull request.

**Comment by Anikulapoo** [comment]
I shall handle this
